[[ics]]
name = "Addr-AFT16V8B"
pins = 20
vcc = 5.0
vectors = [
    "1XXXXXX00G0XXXXXXXXV",

    # /MREQ, /IORQ, /M1 all high
    "110011X00G0HHHHHXXXV",

    # /ROM
    "100011X00G0LHHHHXXXV",
    # /RAM
    "100111X00G0HLHHHXXXV",

    # /IN
    "110001X00G0HHLLHXXXV",
    # /IN, but M1 is low
    "110000X00G0HHHHHXXXV",
    # /OUT
    "111001X00G0HHLHLXXXV",
    # /OUT, but M1 is low
    "111000X00G0HHHHHXXXV",
]
